### ISSUE TITLE
Route Angelo kunnen we niet via oude versie ARLearn openen

### ISSUE THREAD

**Issue by Mediawijsheidtour** [ARLearn/android#29]
In de OBA game 'Mediawijsheid tour' hebben we 10 routes uitgezet. We willen elke route nu checken / testen in de oude versie van ARLearn. 
We maken een run aan per route, cachen de files en testen. Maar bij route Angelo blijft de messagelist leeg! We zagen wel een vreemde depencie bij de introductieboodschap, misschien ligt het daaraan.
Zouden jullie ernaar willen kijken.

De andere routes geven geen probleem.

**Comment by stefaanternier** [comment]
Ik heb de dependency bij "angelo introductie" weg gehaald. Waarschijnlijk had die dependency iets maken met het vroegere systeem waarbij 1 geïntegreerde game gemaakt werd.

De introductie boodschap verschijnt nu...
