### ISSUE TITLE
Tekst aanpassen registratiescherm

### ISSUE THREAD

**Issue by stefaanternier** [ARLearn/android#59]
Er dient een klein tekstje gemaakt te worden voor het registratiescherm.

**Comment by nicozijlstra** [comment]
Voorbeeldtekst REGISTRATIESCHERM:

Welkom bij Mijn Stad Heerlen.
Om de opdrachten in de wandeling te kunnen maken, hebben we je naam of groepsnaam nodig.
Om je de resultaten te kunnen toesturen, moet je je e-mailadres invullen.
Veel plezier en leerzame momenten bij de wandeling!

Open Universiteit Nederland

**Comment by stefaanternier** [comment]
done
![screen shot 2015-09-28 at 13 44 33](https://cloud.githubusercontent.com/assets/888321/10134569/1bac79ee-65e7-11e5-85b2-21164a67ed9b.png)
![screen shot 2015-09-28 at 13 44 41](https://cloud.githubusercontent.com/assets/888321/10134571/1dfe6842-65e7-11e5-8efd-e03fc8981d73.png)
