### ISSUE TITLE
Vraag over kapelletje uit lijst halen

### ISSUE THREAD

**Issue by jeroenstorm** [ARLearn/android#62]
De vraag over het kapelletje staat al vanaf het begin in de lijst. Deze moet pas later verschijnen.

**Comment by stefaanternier** [comment]
deze vraag verschijnt nu wanneer iemand een antwoord heeft gegeven op boodschap "begraafplaats"

**Comment by stefaanternier** [comment]
done, is nu gekoppeld aan het beantwoorden van begraafplaats
