### ISSUE TITLE
Einde spel boodschap maken

### ISSUE THREAD

**Issue by stefaanternier** [ARLearn/android#78]
Boodschap bevat
Gefeliciteerd, je bent aan het einde van het spel...

Knoppen 
(a) resultaten niet op de server 
Zoek een plaats met internet en klik op versturen om je werkjes in te sturen.

(b) resultaten wel op de server
Text: Je resultaten zijn via email opgestuurd, reset je game.

**Comment by stefaanternier** [comment]
Jeroen maakt screenshot,
Stefaan zet item klaar ...

**Comment by jeroenstorm** [comment]
![eind_a](https://cloud.githubusercontent.com/assets/11533836/11182135/b552256a-8c68-11e5-8bf0-a11d677aa1df.png)
![eind_b](https://cloud.githubusercontent.com/assets/11533836/11182136/b5828a98-8c68-11e5-9d82-9a1751262465.png)

---
Je hebt de interactieve wandeling 'Mijn Stad' met succes volbracht.

We hebben een overzicht van jouw opdrachten en antwoorden naar het opgegeven emailadres gestuurd.

Wil je de route nog een keer lopen? Met de button hieronder kun je de wandeling herstarten.
---
Je hebt de interactieve wandeling 'Mijn Stad' met succes volbracht.

Omdat je op dit moment geen internet verbinding hebt hebben we het overzicht van jouw opdrachten en antwoorden nog niet kunnen versturen.

Maak verbinding met een Wifi netwerk en klik op de button hieronder.
---

**Comment by jeroenstorm** [comment]
Als bij Einde B de gegevens verstuurd zijn, dan scherm Einde A tonen (dan weet de speler dat het gelukt is).

**Comment by jeroenstorm** [comment]
![award](https://cloud.githubusercontent.com/assets/11533836/11182171/110b1b50-8c69-11e5-97d2-ac368e36d5b5.png)
